### ISSUE TITLE
Dump Skill Information

### ISSUE THREAD

**Issue by Rodze** [Da-Teach/RaidExtractor#4]
It's not an issue, but a feature request.

Is there any plan to dump skill information?  Or simply dump the entire static_data json file that contains information about dungeon drops, champions skills etc.

We used to be able to get the json directly from the client, but now it's encoded in MessagePack so it's harder.

I see you're taking things directly from memory. Nice job.

Thx.

**Comment by Da-Teach** [comment]
I never actually looked at what else is in the static data. If I have some time I'll see if I can easily dump everything to a json.

**Comment by Da-Teach** [comment]
A complete dump can be found here:
https://raid.thehackerwithin.com/static_data.json

Note that in this case the enum's are integer-values, although not impossible but it'll be some work do dump the appropriate enums.  Interestingly enough, I never expected the damage multipliers to be a string.

Another note, some values seem "very high" (like hero-stats), it's because they are in a special "Fixed" format, which is basically a float/double/decimal stored in a int64-value. To get the actual values, divide them by uint.MaxValue (or 4294967295). Some stats (like hero stats) have additional multipliers attached to them.

**Comment by Rodze** [comment]
Thanks a lot for replying so fast.

The skill multipliers string thing seems counterintuitive indeed. Maybe it's done like that just to obfuscate more and make hacking harder. Each skill also has multiple versions, and each version its associated effects besides the multipliers.

The dump you can do from memory is amazing, completely readable, so it's easier to investigate and automate value extraction.

The offline cache version of the static json uses only one letter or two as keys (to reduce file size I guess), so opening it you don't really know what it is about at all unless you have previously looked at the structure. comparison example: https://user-images.githubusercontent.com/499237/93537805-e7b7ad00-f922-11ea-9d03-8903bc9651d7.png

Again, thanks.

**Comment by JABirchall** [comment]
@Da-Teach I have dumped the full data structures of the appModel if want me to share them.
They are in C++ tho, i dont know if you know C++, but you wont need to manually traverse offsets to dump various amount of data as you want.

**Comment by Da-Teach** [comment]
@JABirchall you probably have the same ones as me ;)  

Most of this tool was done with the help of il2cppdumper. The only small bit of manual reversing was done for the static-pointer to appModel. I will look at it again in the next update of Raid, I might have to modify il2cppdumper to generate the 'native structures' so that it works with the memory-reader that I picked off nuget.

I did notice that at least the version of il2cppdumper that I used was not working on generic classes (like list/dictionary/etc), it fails to get the correct offsets in that case. But it's not a huge problem as they can be guestimated easily.

**Comment by JABirchall** [comment]
Oh i use Il2cppinspector, it generates more useable classes.

https://github.com/djkaty/Il2CppInspector

**Comment by Da-Teach** [comment]
Updated static data:
https://github.com/Da-Teach/RaidStaticData/commit/194a10db849985542bbea0fc67a68809d37ef7d8

Interesting additions seem to be new heroes of some kind, but perhaps they are actually Doomtower bosses.

And something like this?
![image](https://user-images.githubusercontent.com/638492/94477497-46f2a880-01d2-11eb-9bd5-4caf56e0edc7.png)

**Comment by JABirchall** [comment]
Yea, But im planning on making mods for the base game, and then write a bot fully networked without any prerequisites for the game.

**Comment by Da-Teach** [comment]
I wrote one ages ago for Summoners War, a lot of upkeep and way more work. Imho, only interesting if you want to build a lot of accounts to sell them. But for each their own 👍
